### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.ThemeUtils" on path: DexPathList

### ISSUE THREAD

**Issue by schott12521** [hendraanggrian/collapsingtoolbarlayout-subtitle#26]
Seems like its time again to update this to the newest support version, but I think you said elsewhere that you are waiting for support v28 to become stable? Anyway I get this error while trying to use v28, "Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.ThemeUtils" on path: DexPathList"

Thanks for the great library! Note: Excluding the support library did not help either.

For the time being, I basically just created a local version of the library and disabled the line for ThemeUtils and changed the other lines that I needed to in order to compile.

**Comment by hendraanggrian** [comment]
Thanks for going deep as to create a modified local duplicate and report what went wrong. I would suspect that `android.support.design.widget.ThemeUtils` are removed in support library version 28. But since `ThemeUtils` are only used for appcompat theme assertion, it is completely fine to remove the line (assuming that your app theme is indeed appcompat).

As to full support to version 28, as mentioned in #22, will have to wait until it become stable.

**Comment by facundomr** [comment]
Hi @hendraanggrian, how can I find the 27.1.1 version code in order to modify that line?
