### ISSUE TITLE
ellipsize Subtitle

### ISSUE THREAD

**Issue by MeinLieberScholli** [HendraAnggrian/collapsingtoolbarlayout-subtitle#5]
Hi,
is it somehow possible to ellipsize the subtitle?
I've already tried it using TextAppearance, but it's not working. So i assume you are not using TextView...

**Comment by HendraAnggrian** [comment]
Hello there. Like the title itself, the subtitle is not a `TextView`. They are `CharSequence`s drawn using `Canvas`. But you're right I seem to skip the part where I had to ellipsize the subtitle. Let me work on that and thank you for the notice.

**Comment by HendraAnggrian** [comment]
Hey again, I have uploaded version 0.4.2 specifically for subtitle ellipsizing, mimicking the logic of title. Please check if it is working in your case and thank you very much for pointing out the issue.

**Comment by MeinLieberScholli** [comment]
Almost perfect. There is just some padding missing. I suppose 16dp should be enough.
![screenshot_20170510-225533](https://cloud.githubusercontent.com/assets/9082911/25921114/88ea8f5a-35d4-11e7-9ad6-25fac5e43d53.png)
![screenshot_20170510-225545](https://cloud.githubusercontent.com/assets/9082911/25921115/88eb8a72-35d4-11e7-9f02-19b839bc435a.png)

**Comment by HendraAnggrian** [comment]
@MeinLieberScholli As you have already discovered, neither the subtitle or the title has a padding. Unfortunately, so is the standard `CollapsingToolbarLayout`.

#### CollapsingToolbarLayout
![screenshot_1494523501](https://cloud.githubusercontent.com/assets/11507430/25963010/0bb5fbc4-36aa-11e7-83fb-968f1ec7cba1.png)

#### SubtitleCollapsingToolbarLayout
![screenshot_1494523571](https://cloud.githubusercontent.com/assets/11507430/25963015/10b52230-36aa-11e7-94c2-276902947b9a.png)

I could make an extra feature to enable this padding, but as a general rule I think we should all follow Material Design Guideline. What do you think?

**Comment by MeinLieberScholli** [comment]
I didn't know that^^ I was just comparing it to the regular AppBarLayout.
![screenshot_20170512-101606](https://cloud.githubusercontent.com/assets/9082911/25989888/13dfead6-36fe-11e7-9cc1-825c0c6e2f97.png)
![image](https://cloud.githubusercontent.com/assets/9082911/25989915/2543a86c-36fe-11e7-83d7-b15b6110d450.png)
In my opinion, it's a clear violation of the material design guide. It wouldn't be the first time that the CollapsingToolbarLayout has a bug or is missing a feature. I couldn't find any issue regarding that, so i might create one myself in the next few days.

**Comment by HendraAnggrian** [comment]
@MeinLieberScholli I can see your point, but I can't make it the default behavior, mainly because 'CollapsingToolbarLayout' has not yet also use this padding.

So I released version 0.4.4 to enable this padding **only when attr `useCompatPadding` is enabled (or by programatically) and no menu item is visible**. When a menu item is present and visible, I think it's their responsibility to apply the padding.

#### useCorrectPadding without menu item
![screenshot_1494582421](https://cloud.githubusercontent.com/assets/11507430/25993479/4f575938-3734-11e7-90c9-abaccd3b1e2b.png)

#### useCorrectPadding with menu item
![screenshot_1494582425](https://cloud.githubusercontent.com/assets/11507430/25993493/57e2a152-3734-11e7-83bd-1c0c9865fb08.png)

If you decided to make your own 'CollapsingToolbarLayout', please let me know, I kinda wanna see, others' perspectives are always interesting :)

**Comment by ArcherEmiya05** [comment]
Is there a solution now?

**Comment by hendraanggrian** [comment]
@ArcherEmiya05 Yes I believe ellipsize is working now. Comment this thread again if you can't get it to work.
